# Generated by Django 3.2.9 on 2023-07-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todoitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
