# Generated by Django 3.2.9 on 2023-07-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_todoitem_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('0', 'High'), ('1', 'Medium'), ('2', 'Low')], default='1', max_length=10),
        ),
    ]
